title: Highlight
description: A Discord bot that notifies you when a configured word is sent in a channel
baseurl: /Highlight
url: "https://ilovetocode2019.com"
show_full_navigation: true

remote_theme: pmarsceill/just-the-docs

aux_links:
  "GitHub":
    - "https://github.com/ilovetocode2019/Highlight"

footer_content: "Copyright &copy; 2021 ilovetocode. Highlight is licensed under the <a href='https://github.com/ilovetocode2019/Highlight/blob/master/LICENSE'>MIT license</a>."
